name: Environment variables
on: push
env:
  WF_ENV: This is env variables scoped at workflow level

jobs:
  custom-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: This is env variable scoped at job level
    steps:
      - name: step 1 in custom-env job
        env:
          STEP_ENV: This is environment variable scoped at step level
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: step 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  custom-env-2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 in custom-env-2 job
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
